// https://waifu.pics/
export const ALL_WAIFUS = [
  // Jupi
  'https://i.waifu.pics/wRpvaDu.jpg',
  'https://i.waifu.pics/ZPXy_XG.jpg',
  'https://i.waifu.pics/L~qlLcJ.jpg',
  'https://i.waifu.pics/FWE8ggD.png',
  'https://i.waifu.pics/Txwg1-z.png',
  'https://i.waifu.pics/LOR7MBO.jpg',
  'https://i.waifu.pics/tLc5RfN.png',
  'https://i.waifu.pics/aGY3-X6.jpg',
  'https://i.waifu.pics/CNzs4Pd.jpg',
  'https://i.waifu.pics/B-CZCbU.png',
  'https://i.waifu.pics/-WhXn5t.jpg',
  'https://i.waifu.pics/II9WeHB.png',
  'https://i.waifu.pics/ysB8wtC.jpg',
  'https://i.waifu.pics/Weau1RP.jpg',
  'https://i.waifu.pics/n6U5SHh.png',
  'https://i.waifu.pics/jIClgKA.jpg',
  'https://i.waifu.pics/R5n5P7f.png',
  'https://i.waifu.pics/qPWyHQ0.png',
  // Glupi
  'https://i.waifu.pics/vd4XAVZ.jpg',
  'https://i.waifu.pics/ueqBS0o.jpg',
  'https://i.waifu.pics/i~RQhRD.png',
  'https://i.waifu.pics/UyzDyil.jpg',
  'https://i.waifu.pics/ZV7J1WW.png',
  'https://i.waifu.pics/JIQ9QZ_.jpg',
  'https://i.waifu.pics/NOJicBh.png',
  'https://i.waifu.pics/8m-r1_O.png',
  'https://i.waifu.pics/I15h0iO.jpg',
  'https://i.waifu.pics/9seL-Rc.jpg',
  'https://i.waifu.pics/Wc5WkuE.png',
  'https://i.waifu.pics/MHrvoGY.jpg',
  'https://i.waifu.pics/8TL6ycS.jpg',
  'https://i.waifu.pics/WGTA1vN.png',
];
